In [2]:
import numpy as np
import pandas as pd

In [3]:
dmd=pd.read_csv('diamonds.csv')

In [4]:
print(dmd.shape)

(50000, 10)

In [ ]:
#1 Load the dataset and display the first 10 rows.
dmd.head(10)

   carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [ ]:
#2 Check the shape and column names of the dataset
print(dmd.shape)
dmd.columns

(50000, 10)

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [11]:
#3 Find and fill missing numeric values with their respective column means
dmd.loc[2:10,'depth']=np.nan
# print("after insertion of nan values")
# dmd.head(20)
# print("after insertion of the mean")
dmd['depth']=dmd['depth'].fillna(dmd['depth'].mean())
dmd.head(20)      #DOUBTS

,carat,cut,color,clarity,depth,table,price,x,y,z,price_updated,volume
0,0.23,Ideal,E,SI2,61.50000,55.0,326,3.95,3.98,2.43,358.6,38.202030
1,0.21,Premium,E,SI1,59.80000,61.0,326,3.89,3.84,2.31,358.6,34.505856
2,0.23,Good,E,VS1,61.75296,65.0,327,4.05,4.07,2.31,359.7,38.076885
3,0.29,Premium,I,VS2,61.75296,58.0,334,4.20,4.23,2.63,367.4,46.724580
4,0.31,Good,J,SI2,61.75296,58.0,335,4.34,4.35,2.75,368.5,51.917250
5,0.24,Very Good,J,VVS2,61.75296,57.0,336,3.94,3.96,2.48,369.6,38.693952
6,0.24,Very Good,I,VVS1,61.75296,57.0,336,3.95,3.98,2.47,369.6,38.830870
7,0.26,Very Good,H,SI1,61.75296,55.0,337,4.07,4.11,2.53,370.7,42.321081
8,0.22,Fair,E,VS2,61.75296,61.0,337,3.87,3.78,2.49,370.7,36.425214
9,0.23,Very Good,H,VS1,61.75296,61.0,338,4.00,4.05,2.39,371.8,38.718000
10,0.30,Good,J,SI1,61.75296,55.0,339,4.25,4.28,2.73,372.9,49.658700
11,0.23,Ideal,J,VS1,62.80000,56.0,340,3.93,3.90,2.46,374.0,37.704420
12,0.22,Premium,F,SI1,60.40000,61.0,342,3.88,3.84,2.33,376.2,34.715136
13,0.31,Ideal,J,SI2,62.20000,54.0,344,4.35,4.37,2.71,378.4,51.515745
14,0.20,Premium,E,SI2,60.20000,62.0,345,3.79,3.75,2.27,379.5,32.262375
15,0.32,Premium,E,I1,60.90000,58.0,345,4.38,4.42,2.68,379.5,51.883728
16,0.30,Ideal,I,SI2,62.00000,54.0,348,4.31,4.34,2.68,382.8,50.130472
17,0.30,Good,J,SI1,63.40000,54.0,351,4.23,4.29,2.70,386.1,48.996090
18,0.30,Good,J,SI1,63.80000,56.0,351,4.23,4.26,2.71,386.1,48.833658
19,0.30,Very Good,J,SI1,62.70000,59.0,351,4.21,4.27,2.66,386.1,47.818022

In [ ]:
#4 Filter rows where `cut` is "Ideal" and `color` is "E".
sec_dmd=dmd[(dmd['cut']=='Ideal')&(dmd['color']=='E')]
display(sec_dmd)
print(sec_dmd.shape)

       carat    cut color clarity  depth  table  price     x     y     z
0       0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
76      0.26  Ideal     E    VVS2   62.9   58.0    554  4.02  4.06  2.54
82      0.70  Ideal     E     SI1   62.5   57.0   2757  5.70  5.72  3.57
100     0.59  Ideal     E    VVS2   62.0   55.0   2761  5.38  5.43  3.35
102     0.74  Ideal     E     SI2   62.2   56.0   2761  5.80  5.84  3.62
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
49940   0.70  Ideal     E     SI1   61.7   55.0   2745  5.71  5.74  3.53
49942   0.51  Ideal     E    VVS1   61.9   54.0   2745  5.17  5.11  3.18
49954   0.56  Ideal     E    VVS1   62.1   56.0   2750  5.28  5.29  3.28
49978   0.77  Ideal     E     SI2   62.1   56.0   2753  5.84  5.86  3.63
49987   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54

[3628 rows x 10 columns]

(3628, 10)

In [ ]:
#5 Group by `cut` and compute the average `price` for each group.
thd_dmd=dmd.groupby(['cut'])['price'].mean()
display(thd_dmd)

cut
Fair         4329.705017
Good         3961.470266
Ideal        3463.090230
Premium      4607.382867
Very Good    3986.585594
Name: price, dtype: float64

In [ ]:
#6 Sort the data by `carat` in descending order and show the top 5 rows.
for_dmd=dmd.sort_values(['carat'],ascending=False)
for_dmd.head(20)

       carat        cut color clarity  depth  table  price      x      y     z
25426   5.01       Fair     J      I1   65.5   59.0  18018  10.74  10.54  6.98
25624   4.50       Fair     J      I1   65.8   58.0  18531  10.23  10.16  6.72
25163   4.13       Fair     H      I1   64.8   61.0  17329  10.00   9.85  6.43
24103   4.01    Premium     J      I1   62.5   62.0  15223  10.02   9.94  6.24
24102   4.01    Premium     I      I1   61.0   61.0  15223  10.14  10.10  6.17
24529   4.00  Very Good     I      I1   63.3   58.0  15984  10.01   9.94  6.31
24612   3.67    Premium     I      I1   62.4   56.0  16193   9.86   9.81  6.13
21909   3.65       Fair     H      I1   67.1   53.0  11668   9.53   9.48  6.38
25669   3.51    Premium     J     VS2   62.5   59.0  18701   9.66   9.63  6.03
22540   3.50      Ideal     H      I1   62.8   57.0  12587   9.65   9.59  6.03
24518   3.40       Fair     D      I1   66.8   52.0  15964   9.42   9.34  6.27
22357   3.24    Premium     H      I1   62.1   58.0  12300   9.44   9.40  5.85
22512   3.22      Ideal     I      I1   62.6   55.0  12545   9.49   9.42  5.92
20145   3.11       Fair     J      I1   65.9   57.0   9823   9.15   9.02  5.98
20776   3.05    Premium     E      I1   60.9   58.0  10453   9.26   9.25  5.66
24199   3.04  Very Good     I     SI2   63.2   59.0  15354   9.14   9.07  5.75
25632   3.04    Premium     I     SI2   59.3   60.0  18559   9.51   9.46  5.62
20882   3.02       Fair     I      I1   65.2   56.0  10577   9.11   9.02  5.91
25642   3.01       Good     H     SI2   57.6   64.0  18593   9.44   9.38  5.42
17893   3.01    Premium     I      I1   62.7   58.0   8040   9.10   8.97  5.67

In [25]:
#7 Convert the `price` column to a NumPy array and find its mean, median, and standard deviation.
dmd['price'].describe()# describe function is used to find the values of the mean, median, standard deviation
# DOUBT

count    50000.000000
mean      3944.805440
std       3997.938105
min        326.000000
25%        951.000000
50%       2410.000000
75%       5351.000000
max      18823.000000
Name: price, dtype: float64

In [ ]:
#8 Count diamonds with `price > 5000` and `carat > 1` using NumPy conditions.
dmd.columns
five_dmd=dmd[(dmd['price']>5000)&(dmd['carat']>1)]
print(five_dmd.shape)#Not Sure

(12798, 10)

In [7]:
#9  Create a new column `price_updated` by increasing `price` by 10% using NumPy
dmd['price_updated']=(dmd['price']+(dmd['price']*0.1))
dmd.head(20)

,carat,cut,color,clarity,depth,table,price,x,y,z,price_updated
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,358.6
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,358.6
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,359.7
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,367.4
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,368.5
5,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,369.6
6,0.24,Very Good,I,VVS1,62.3,57.0,336,3.95,3.98,2.47,369.6
7,0.26,Very Good,H,SI1,61.9,55.0,337,4.07,4.11,2.53,370.7
8,0.22,Fair,E,VS2,65.1,61.0,337,3.87,3.78,2.49,370.7
9,0.23,Very Good,H,VS1,59.4,61.0,338,4.00,4.05,2.39,371.8
10,0.30,Good,J,SI1,64.0,55.0,339,4.25,4.28,2.73,372.9
11,0.23,Ideal,J,VS1,62.8,56.0,340,3.93,3.90,2.46,374.0
12,0.22,Premium,F,SI1,60.4,61.0,342,3.88,3.84,2.33,376.2
13,0.31,Ideal,J,SI2,62.2,54.0,344,4.35,4.37,2.71,378.4
14,0.20,Premium,E,SI2,60.2,62.0,345,3.79,3.75,2.27,379.5
15,0.32,Premium,E,I1,60.9,58.0,345,4.38,4.42,2.68,379.5
16,0.30,Ideal,I,SI2,62.0,54.0,348,4.31,4.34,2.68,382.8
17,0.30,Good,J,SI1,63.4,54.0,351,4.23,4.29,2.70,386.1
18,0.30,Good,J,SI1,63.8,56.0,351,4.23,4.26,2.71,386.1
19,0.30,Very Good,J,SI1,62.7,59.0,351,4.21,4.27,2.66,386.1

In [9]:
#10  Create a `volume` column as `x*y*z` and find the average `price` where `volume > 50`
dmd.head()
dmd["volume"]=(dmd["x"]*dmd["y"]*dmd["z"])
dmd.head()

,carat,cut,color,clarity,depth,table,price,x,y,z,price_updated,volume
0,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,358.6,38.202030
1,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,358.6,34.505856
2,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31,359.7,38.076885
3,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,367.4,46.724580
4,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,368.5,51.917250